services:
  recipot-mariadb:
    container_name: recipot-mariadb
    image: mariadb:10.8.2
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: recipot
      MYSQL_USER: recipot
      MYSQL_PASSWORD: recipot1!11
      MYSQL_ROOT_PASSWORD: recipot1!11
      TZ: Asia/Seoul
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    networks:
      - docker-network
    restart: always

  recipot-redis:
    container_name: recipot-redis
    image: redis:7.2.4-alpine3.19
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/user.acl:/usr/local/etc/redis/user.acl
    networks:
      - docker-network
    restart: always

  recipot-nginx:
    container_name: recipot-nginx
    image: nginx:1.25.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - docker-network
    restart: always
  
  recipot-api:
    container_name: recipot-api
    image: 488599977281.dkr.ecr.ap-northeast-2.amazonaws.com/my-project-api:${IMAGE_TAG}
    command: yarn run start:prod
    env_file:
      - .env
      - .env.production
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_CONNECTION_HOST=${REDIS_CONNECTION_HOST}
      - REDIS_CONNECTION_PWD=${REDIS_CONNECTION_PWD}
      - IMAGE_TAG=${IMAGE_TAG}
    ports:
      - "8080:8080"
    volumes:
      - ./docker/log:/app/dist/log
    depends_on:
      - recipot-mariadb
      - recipot-redis
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    external: true