import { DataSource } from 'typeorm';
import { CommonCode } from '../entity/common-code.entity';

export class CommonCodeSeed {
  constructor(private dataSource: DataSource) {}

  async run(): Promise<void> {
    if (!this.dataSource || !this.dataSource.manager) {
      throw new Error('DataSource or manager is not available');
    }

    const commonCodeRepository =
      this.dataSource.manager.getRepository(CommonCode);

    const commonCodes = [
      {
        groupCode: 'C01',
        groupCodeName: 'PLATFORM',
        code: 'C01001',
        codeName: 'kakao',
        groupName: '플랫폼',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'C01',
        groupCodeName: 'PLATFORM',
        code: 'C01002',
        codeName: 'google',
        groupName: '플랫폼',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'U01',
        groupCodeName: 'USER_ROLE',
        code: 'U01001',
        codeName: 'admin',
        groupName: '유저 역할',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'U01',
        groupCodeName: 'USER_ROLE',
        code: 'U01002',
        codeName: 'paid',
        groupName: '유저 역할',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'U01',
        groupCodeName: 'USER_ROLE',
        code: 'U01003',
        codeName: 'general',
        groupName: '유저 역할',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'R01',
        groupCodeName: 'TIME_TAKEN',
        code: 'R01001',
        codeName: '5',
        groupName: '소요 시간',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'R01',
        groupCodeName: 'TIME_TAKEN',
        code: 'R01002',
        codeName: '10',
        groupName: '소요 시간',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'R01',
        groupCodeName: 'TIME_TAKEN',
        code: 'R01003',
        codeName: '15',
        groupName: '소요 시간',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'R01',
        groupCodeName: 'TIME_TAKEN',
        code: 'R01004',
        codeName: '30',
        groupName: '소요 시간',
        depth: 1,
        orderNum: 4,
        isActive: true,
      },
      {
        groupCode: 'R02',
        groupCodeName: 'COOKING_DIFFICULTY',
        code: 'R02001',
        codeName: '초보',
        groupName: '조리 난이도',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'R02',
        groupCodeName: 'COOKING_DIFFICULTY',
        code: 'R02002',
        codeName: '중수',
        groupName: '조리 난이도',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'R02',
        groupCodeName: 'COOKING_DIFFICULTY',
        code: 'R02003',
        codeName: '고수',
        groupName: '조리 난이도',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'R03',
        groupCodeName: 'REVIEW_TASTE',
        code: 'R03001',
        codeName: '별로였어요',
        groupName: '후기 맛 평가',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'R03',
        groupCodeName: 'REVIEW_TASTE',
        code: 'R03002',
        codeName: '그저 그래요',
        groupName: '후기 맛 평가',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'R03',
        groupCodeName: 'REVIEW_TASTE',
        code: 'R03003',
        codeName: '맛있었어요',
        groupName: '후기 맛 평가',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'R04',
        groupCodeName: 'REVIEW_START_COOKING',
        code: 'R04001',
        codeName: '부담스러웠어요',
        groupName: '요리 시작 난이도',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'R04',
        groupCodeName: 'REVIEW_START_COOKING',
        code: 'R04002',
        codeName: '보통이었어요',
        groupName: '요리 시작 난이도',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'R04',
        groupCodeName: 'REVIEW_START_COOKING',
        code: 'R04003',
        codeName: '쉬웠어요',
        groupName: '요리 시작 난이도',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'R05',
        groupCodeName: 'REVIEW_COOKING_EXPERIENCE',
        code: 'R05001',
        codeName: '복잡했어요',
        groupName: '직접 요리해보니',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'R05',
        groupCodeName: 'REVIEW_COOKING_EXPERIENCE',
        code: 'R05002',
        codeName: '보통이었어요',
        groupName: '직접 요리해보니',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'R05',
        groupCodeName: 'REVIEW_COOKING_EXPERIENCE',
        code: 'R05003',
        codeName: '간단했어요',
        groupName: '직접 요리해보니',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'H01',
        groupCodeName: 'HEALTH_PERSISTENT_ISSUE',
        code: 'H01001',
        codeName: '더 심해졌어요.',
        groupName: '평소 겪던 건강 문제',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'H01',
        groupCodeName: 'HEALTH_PERSISTENT_ISSUE',
        code: 'H01002',
        codeName: '전과 비슷해요.',
        groupName: '평소 겪던 건강 문제',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'H01',
        groupCodeName: 'HEALTH_PERSISTENT_ISSUE',
        code: 'H01003',
        codeName: '개선됨을 느껴요.',
        groupName: '평소 겪던 건강 문제',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },

      // Health survey - effects (H02)
      {
        groupCode: 'H02',
        groupCodeName: 'HEALTH_PERCEIVED_EFFECT',
        code: 'H02001',
        codeName: '피로가 줄었다.',
        groupName: '느낀 변화',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'H02',
        groupCodeName: 'HEALTH_PERCEIVED_EFFECT',
        code: 'H02002',
        codeName: '몸이 가벼워졌다.',
        groupName: '느낀 변화',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'H02',
        groupCodeName: 'HEALTH_PERCEIVED_EFFECT',
        code: 'H02003',
        codeName: '속이 편했다.',
        groupName: '느낀 변화',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'H02',
        groupCodeName: 'HEALTH_PERCEIVED_EFFECT',
        code: 'H02004',
        codeName: '체중 관리에 도움이 된다.',
        groupName: '느낀 변화',
        depth: 1,
        orderNum: 4,
        isActive: true,
      },
      {
        groupCode: 'H02',
        groupCodeName: 'HEALTH_PERCEIVED_EFFECT',
        code: 'H02005',
        codeName: '기타',
        groupName: '느낀 변화',
        depth: 1,
        orderNum: 5,
        isActive: true,
      },

      // Measurement Guide Category (M01)
      {
        groupCode: 'M01',
        groupCodeName: 'MEASUREMENT_CATEGORY',
        code: 'M01001',
        codeName: '가루류',
        groupName: '계량 가이드 카테고리',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'M01',
        groupCodeName: 'MEASUREMENT_CATEGORY',
        code: 'M01002',
        codeName: '장,젓갈류',
        groupName: '계량 가이드 카테고리',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'M01',
        groupCodeName: 'MEASUREMENT_CATEGORY',
        code: 'M01003',
        codeName: '액체류',
        groupName: '계량 가이드 카테고리',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'M01',
        groupCodeName: 'MEASUREMENT_CATEGORY',
        code: 'M01004',
        codeName: '그외',
        groupName: '계량 가이드 카테고리',
        depth: 1,
        orderNum: 4,
        isActive: true,
      },

      // Nickname Adjective (U02)
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02001',
        codeName: '발랄한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 1,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02002',
        codeName: '속깊은',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 2,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02003',
        codeName: '현명한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 3,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02004',
        codeName: '따뜻한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 4,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02005',
        codeName: '자상한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 5,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02006',
        codeName: '유쾌한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 6,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02007',
        codeName: '정직한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 7,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02008',
        codeName: '성실한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 8,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02009',
        codeName: '열정적인',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 9,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02010',
        codeName: '진중한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 10,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02011',
        codeName: '똑똑한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 11,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02012',
        codeName: '차분한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 12,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02013',
        codeName: '재치있는',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 13,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02014',
        codeName: '유능한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 14,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02015',
        codeName: '친절한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 15,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02016',
        codeName: '용감한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 16,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02017',
        codeName: '겸손한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 17,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02018',
        codeName: '명랑한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 18,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02019',
        codeName: '든든한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 19,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02020',
        codeName: '성숙한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 20,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02021',
        codeName: '다정한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 21,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02022',
        codeName: '힙스터',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 22,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02023',
        codeName: '갓생러',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 23,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02024',
        codeName: '멋쟁이',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 24,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02025',
        codeName: '핵인싸',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 25,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02026',
        codeName: '귀여운',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 26,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02027',
        codeName: '시크한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 27,
        isActive: true,
      },
      {
        groupCode: 'U02',
        groupCodeName: 'NICKNAME_ADJ',
        code: 'U02028',
        codeName: '순수한',
        groupName: '닉네임 형용사',
        depth: 1,
        orderNum: 28,
        isActive: true,
      },
    ];

    for (const commonCodeData of commonCodes) {
      const existingCode = await commonCodeRepository.findOne({
        where: { code: commonCodeData.code },
      });

      if (!existingCode) {
        const commonCode = commonCodeRepository.create(commonCodeData);
        await commonCodeRepository.save(commonCode);
      }
    }
  }
}
