name: Setup Infisical CLI

on:
  workflow_dispatch: {}

jobs:
  install-infisical:
    runs-on: ubuntu-latest
    steps:
      - name: Download & Install Infisical CLI
        run: |
          curl -L https://github.com/Infisical/infisical/releases/download/infisical-cli%2Fv0.41.6/infisical_0.41.6_linux_amd64.tar.gz -o infisical.tar.gz
          tar -xzf infisical.tar.gz
          chmod +x infisical
          mkdir -p ~/.infisical-bin
          mv infisical ~/.infisical-bin/infisical

      - name: Verify Infisical CLI
        run: ~/.infisical-bin/infisical --version

      - name: Cache CLI Binary
        uses: actions/cache@v4
        with:
          path: ~/.infisical-bin/infisical
          key: infisical-cli-cache-v3
