name: Setup Infisical CLI

on:
  workflow_dispatch: {}

jobs:
  install-infisical:
    runs-on: ubuntu-latest
    steps:
      - name: Download & Install Infisical CLI
        run: |
          curl -L https://github.com/infisical/infisical/releases/latest/download/infisical-linux-amd64 \
            -o infisical
          chmod +x infisical
          mkdir -p ~/.infisical-bin
          mv infisical ~/.infisical-bin/infisical

      - name: Cache Infisical CLI
        uses: actions/cache@v4
        with:
          path: ~/.infisical-bin/infisical
          key: infisical-cli-cache-v1
